### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by romanrehacek** [uniibu/theia-vue-extension#4]
Hi,

after installing your plugin and 3 dependencies, I get error in my console.
```
module.js:550
    throw err;
    ^
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.defineProperty.value (/tmp/vscode-unpacked/vscode-builtin-html-language-features-0.1.0.tgz/package/server/dist/htmlServerMain.js:8:156852)
    at n (/tmp/vscode-unpacked/vscode-builtin-html-language-features-0.1.0.tgz/package/server/dist/htmlServerMain.js:1:220)
    at Object.<anonymous> (/tmp/vscode-unpacked/vscode-builtin-html-language-features-0.1.0.tgz/package/server/dist/htmlServerMain.js:8:149158)
    at n (/tmp/vscode-unpacked/vscode-builtin-html-language-features-0.1.0.tgz/package/server/dist/htmlServerMain.js:1:220)
    at Object.defineProperty.value (/tmp/vscode-unpacked/vscode-builtin-html-language-features-0.1.0.tgz/package/server/dist/htmlServerMain.js:8:146802)
    at n (/tmp/vscode-unpacked/vscode-builtin-html-language-features-0.1.0.tgz/package/server/dist/htmlServerMain.js:1:220)
[Info  - 16:03:11] Connection to server got closed. Server will restart.
module.js:550
```

Can you help me?

I run theia in Docker with this package.json
```
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/core": "next",
    "@theia/editor": "next",
    "@theia/editorconfig": "next",
    "@theia/file-search": "next",
    "@theia/filesystem": "next",
    "@theia/git": "next",
    "@theia/json": "next",
    "@theia/keymaps": "next",
    "@theia/languages": "next",
    "@theia/markers": "next",
    "@theia/merge-conflicts": "next",
    "@theia/messages": "next",
    "@theia/mini-browser": "next",
    "@theia/monaco": "next",
    "@theia/navigator": "next",
    "@theia/outline-view": "next",
    "@theia/php": "next",
    "@theia/output": "next",
    "@theia/plugin": "next",
    "@theia/plugin-ext": "next",
    "@theia/plugin-ext-vscode": "next",
    "@theia/preferences": "next",
    "@theia/process": "next",
    "@theia/search-in-workspace": "next",
    "@theia/task": "next",
    "@theia/terminal": "next",
    "@theia/textmate-grammars": "next",
    "@theia/tslint": "next",
    "@theia/typescript": "next",
    "@theia/userstorage": "next",
    "@theia/workspace": "next",
    "@devpodio/theia-vue-extension": "0.2.1",
    "@theia/metrics": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```

I added this plugins 
- vscode-builtin-css-language-features-0.1.0.tgz
- vscode-builtin-emmet-0.1.0.tgz
- vscode-builtin-html-language-features-0.1.0.tgz
- vscode-builtin-typescript-0.1.0.tgz

**Comment by uniibu** [comment]
On Dockerfile, simply install typescript globally.. `RUN npm install typescript -g`
